"""empty message

Revision ID: b570e6844c3a
Revises: 
Create Date: 2023-03-04 14:01:59.672715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b570e6844c3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt', sa.String(length=500), nullable=True),
    sa.Column('choice_1', sa.String(length=255), nullable=True),
    sa.Column('choice_2', sa.String(length=255), nullable=True),
    sa.Column('choice_3', sa.String(length=255), nullable=True),
    sa.Column('choice_4', sa.String(length=255), nullable=True),
    sa.Column('correct_answer', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
